# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-20 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log_reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('one_user_who_uploaded_this_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_uploaded', to='log_reg.User')),
                ('users_who_like_this_book', models.ManyToManyField(related_name='books_liked', to='log_reg.User')),
            ],
        ),
    ]
